version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: skillpass-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: edutrust
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: skillpass-api
    restart: always
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      DATABASE_URL: mysql://root:rootpassword@mysql-db:3306/edutrust
      JWT_SALT: my_super_secret_jwt_salt
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data:
